const watchlistData = [
  {
    id: 1,
    company: "Reliance",
    sector: "Energy",
    marketCap: "Large",
    trend: "medium",
  },
  {
    id: 2,
    company: "Tata",
    sector: "IT",
    marketCap: "Large",
    trend: "weak",
  },
  {
    id: 3,
    company: "HDFC",
    sector: "Finance",
    marketCap: "Large",
    trend: "strong",
  },
  {
    id: 4,
    company: "Bharti Airtel",
    sector: "Telecom",
    marketCap: "Large",
    trend: "weak",
  },
  {
    id: 5,
    company: "Adani Ent",
    sector: "Energy",
    marketCap: "Large",
    trend: "strong",
  },
  {
    id: 6,
    company: "Wipro",
    sector: "IT",
    marketCap: "Large",
    trend: "medium",
  },
  {
    id: 7,
    company: "Biocon",
    sector: "Healthcare",
    marketCap: "Mid",
    trend: "weak",
  },
  {
    id: 8,
    company: "GAIL",
    sector: "Energy",
    marketCap: "Mid",
    trend: "strong",
  },
  {
    id: 9,
    company: "The India Cements",
    sector: "Cement",
    marketCap: "Small",
    trend: "medium",
  },
  {
    id: 10,
    company: "Infosys",
    sector: "IT",
    marketCap: "Large",
    trend: "strong",
  },
  {
    id: 11,
    company: "Reliance",
    sector: "Energy",
    marketCap: "Large",
    trend: "medium",
  },
  {
    id: 12,
    company: "Tata",
    sector: "IT",
    marketCap: "Large",
    trend: "weak",
  },
  {
    id: 13,
    company: "HDFC",
    sector: "Finance",
    marketCap: "Large",
    trend: "strong",
  },
  {
    id: 14,
    company: "Bharti Airtel",
    sector: "Telecom",
    marketCap: "Large",
    trend: "weak",
  },
  {
    id: 15,
    company: "Adani Ent",
    sector: "Energy",
    marketCap: "Large",
    trend: "strong",
  },
  {
    id: 16,
    company: "Wipro",
    sector: "IT",
    marketCap: "Large",
    trend: "medium",
  },
  {
    id: 17,
    company: "Biocon",
    sector: "Healthcare",
    marketCap: "Mid",
    trend: "weak",
  },
  {
    id: 18,
    company: "GAIL",
    sector: "Energy",
    marketCap: "Mid",
    trend: "strong",
  },
  {
    id: 19,
    company: "The India Cements",
    sector: "Cement",
    marketCap: "Small",
    trend: "medium",
  },
  {
    id: 20,
    company: "Infosys",
    sector: "IT",
    marketCap: "Large",
    trend: "strong",
  },
];

export default watchlistData;
